# Generated by Django 5.1.7 on 2025-03-12 01:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_pic'),
        ),
    ]
